# Generated by Django 3.1.3 on 2021-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCSSC_branch_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('head_office', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('manager', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BooleanField(default=True)),
            ],
        ),
    ]
