# Generated by Django 3.1.3 on 2021-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocssc_branch_office',
            name='created_by',
            field=models.BooleanField(default=True),
        ),
    ]
